services:

    oc_user.registration_listener:
        class: OC\UserBundle\EventListener\EmailConfirmationListener
        arguments:    ["@fos_user.mailer", "@fos_user.util.token_generator", "@router", "@session"]
        tags:
            - { name: kernel.event_subscriber }
#    oc_user.example:
#        class: OC\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
