<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function getAdverts()
  {
    $query = $this->createQueryBuilder('a')
      // Jointure sur l'attribut imageHeader
      //->leftJoin('a.imageheader', 'i')
      //->addSelect('i')
      // Jointure sur l'attribut categories
      /*
      ->leftJoin('a.categories', 'c')
      ->addSelect('c')
      ->orderBy('a.date', 'DESC')
      */
      ->leftJoin('a.imagecontents', 'd')
      ->addSelect('d')
      ->orderBy('a.id', 'DESC')

      ->getQuery();

    return $query->getResult();
  }

 public function getPublishedQueryBuilder()
  {
    return $this
      ->createQueryBuilder('a')
      ->where('a.published = :published')
      ->setParameter('published', true)
    ;
  }
}
